## Definition of System of Equations
-------------------------
A set of simultaneous equations, usually referred to as a system of equations or an equation system, is a finite collection of equations for which common solutions are sought in mathematics. i.e same set of solution satifies every equation in the system.

**Types:**
- System of linear equations
- System of nonlinear equations
- System of bilinear equations
- System of polynomial equations
- System of differential equations
- System of difference equations


In [1]:
import numpy as np

#### Pre-required Functions to required to code Guass - Jordan & Gauss Elimination method

In [2]:
def interchange(M,i,j):
    a = M[i].copy()
    M[i] = M[j]
    M[j] = a
    return M

def subtractRow(M,i,j,k):
    M[i] = M[i] - k*M[j]
    return M

def echelon(M):
    r = len(M)
    c = len(M[0])
    #print(M)
    
    if M[0,0] == 0:
        for i in range(r):
            if M[i,0] != 0:
                M = interchange(M,0,i)
                break
    if M[0,0] == 0:
        if c==1:
            return M
        else:
            M[:,1:] = echelon(M[:,1:])
            
    else:
        M[0] = M[0]/M[0,0]
        if r>1:
            for i in range(1,r):
                M = subtractRow(M,i,0,M[i,0])
            if c>1:
                M[1:,1:] = echelon(M[1:,1:])
            else:
                return M
        else:
            return M
        
    return M

def rowReducedEchelon(M):
    #print(M)
    M = echelon(M)
    r = len(M)
    c = len(M[0])
    
    # loop 'i' is to traverse rows
    # loop 'j' is to traverse elements of i th row to find the leading element of i th row
    # loop 'k' is to make the j th elements of (i-1) rows as zero
    
    for i in range(r):
        for j in range(c):
            if M[i,j] == 1:
                for k in range(i):
                    M = subtractRow(M,k,i,M[k,j])
                break
    #print(M)             
    return M   


def inverse(M):
    n = len(M)
    I = np.identity(n)
    
    if np.linalg.matrix_rank(M)==n:
        b=np.concatenate((M, I), axis=1)
        B1=rowReducedEchelon(b)
        print(B1[:,n: ])
    
    else:
        print("Inverse does not exist..!")

### 1] Write a python program to find the solution of a system of equation using Gauss Jordan method.
-------------

In [3]:
"""

Title: SOLVING SYSTEM OF EQAUATIONS USING GAUSS JORDAN METHOD
Input: Matrix A and Matrix B (System of equations in matrix for)
Output: Solution for system of equations
Developed By: Naveen N S

"""

def matrix1():
    r = int(input("Enter number of rows for matrix 1: "))
    c = int(input("Enter number of columns for matrix 1: "))

    value=[[int(input('Enter the values for matrix 1: '))for i in range(c)]for j in range(r)]
    
    global matrix1
    matrix1= np.array(value).reshape(r,c)
    
    return matrix1

def matrix2():
    r = int(input("Enter number of rows for matrix 2: "))
    c = int(input("Enter number of columns for matrix 2: "))

    value=[[int(input('Enter the values for matrix 2: '))for i in range(c)]for j in range(r)]
    
    global matrix2
    matrix2= np.array(value).reshape(r,c)
    
    return matrix2


def gauss_jordan(A,B):
    r = len(A)
    c = len(A[0])
    
    M = np.concatenate((A,B),axis=1);
    M = rowReducedEchelon(M);
    
    x = np.zeros(c)  # np.ones(c)
    
    for i in range(r-1,-1,-1):
        if np.all(M[i] == 0):
            continue
        elif np.all(M[i,0:c]) == 0:
            print("The System is Inconsistent..!");
            continue
        for j in range(c):
            if M[i,j] == 1:
                k=j
                break
        
        temp = 0
        
        for j in range(c-1,k,-1):
            temp += M[i,j]*x[j]
        x[i] = M[i,c] - temp
        
    if np.all(M[i,0:c]) != 0:
        for h in range(len(x)):
            print("X{} =".format(h),int(x[h]))
            
A = matrix1()           
print("*"*50)
print("MATRIX A".center(50))
print("*"*50)
print(A)
print()
print("-"*50)

B = matrix2()
print("*"*50)
print("MATRIX B".center(50))
print("*"*50)
print(B)

print("*"*50)
print("SOLUTION USING GAUSS-JORDAN".center(50))
print("*"*50)         
gauss_jordan(A,B)  
print("*"*50)
print("PROGRAM ENDED".center(50))
print("*"*50)

Enter number of rows for matrix 1: 2
Enter number of columns for matrix 1: 2
Enter the values for matrix 1: 4
Enter the values for matrix 1: 4
Enter the values for matrix 1: 2
Enter the values for matrix 1: 2
**************************************************
                     MATRIX A                     
**************************************************
[[4 4]
 [2 2]]

--------------------------------------------------
Enter number of rows for matrix 2: 2
Enter number of columns for matrix 2: 1
Enter the values for matrix 2: 20
Enter the values for matrix 2: 10
**************************************************
                     MATRIX B                     
**************************************************
[[20]
 [10]]
**************************************************
           SOLUTION USING GAUSS-JORDAN            
**************************************************
X0 = 5
X1 = 0
**************************************************
                  PROGRAM ENDED           

### 2] Write a python program to find the solution of a system of equation using Gauss elimination method.
---------------------

In [4]:
"""

Title: SOLVING SYSTEM OF EQAUATIONS USING GAUSS ELIMINATION METHOD
Input: Matrix A and Matrix B (System of equations in matrix for)
Output: Solution for system of equations
Developed By: Naveen N S

"""

def gauss_elimination(A,B):
    r = len(A)
    c = len(A[0])
    
    M = np.concatenate((A,B),axis=1);
    M = echelon(M);
    
    x = np.zeros(c)  # np.ones(c)
    
    for i in range(r-1,-1,-1):
        if np.all(M[i] == 0):
            continue
        elif np.all(M[i,0:c]) == 0:
            print("The System is Inconsistent..!");
            break
        for j in range(c):
            if M[i,j] == 1:
                k=j
                break
        
        temp = 0
        
        for j in range(c-1,k,-1):
            temp += M[i,j]*x[j]
        x[i] = M[i,c] - temp
        
    if np.all(M[i,0:c]) != 0:
        for h in range(len(x)):
            print("X{} =".format(h),int(x[h]))

print("*"*50)
print("SOLUTION USING GAUSS-ELIMINATION".center(50))
print("*"*50)         
gauss_elimination(A,B) 
print("*"*50)
print("PROGRAM ENDED".center(50))
print("*"*50)

**************************************************
         SOLUTION USING GAUSS-ELIMINATION         
**************************************************
X0 = 5
X1 = 0
**************************************************
                  PROGRAM ENDED                   
**************************************************


## Direct Method available in Numpy
--------------------------------

In [6]:
"""

Title: SOLVING SYSTEM OF EQAUATIONS USING NUMPY LEAST SQUARE KEYWORD
Input: Matrix A and Matrix B (System of equations in matrix for)
Output: Solution for system of equations
Developed By: Naveen N S

"""
print("*"*50)
print("SOLUTION USING LINALG LEAST SQUARE OF NUMPY".center(50))
print("*"*50)   
print(np.linalg.lstsq(A,B,rcond=None)[0])
print("*"*50)
print("PROGRAM ENDED".center(50))
print("*"*50)

**************************************************
   SOLUTION USING LINALG LEAST SQUARE OF NUMPY    
**************************************************
[[2.5]
 [2.5]]
**************************************************
                  PROGRAM ENDED                   
**************************************************


In [7]:
"""

Title: SOLVING SYSTEM OF EQAUATIONS USING NUMPY SOLVE KEYWORD
Input: Matrix A and Matrix B (System of equations in matrix for)
Output: Solution for system of equations
Developed By: Naveen N S

"""

# will solve only when the solutions are unique,and the matrices are square-invertible matrices
# i.e we get an error if the co-efficient matrix turn out to be a singlular matrix

print("*"*50)
print("SOLUTION USING LINALG SOLVE OF NUMPY".center(50))
print("*"*50)  
try:
    print(np.linalg.solve(A,B))
except:
    print("Cannot use this method as the co-efficient matrix is a singluar matrix")
print("*"*50)
print("PROGRAM ENDED".center(50))
print("*"*50)

**************************************************
       SOLUTION USING LINALG SOLVE OF NUMPY       
**************************************************
Cannot use this method as the co-efficient matrix is a singluar matrix
**************************************************
                  PROGRAM ENDED                   
**************************************************
